.\"                                      Hey, EMACS: -*- nroff -*-
.TH acct-meta 1 "29 Oct 2013" "acct-meta 0.1"

.SH NAME
acct-meta-json \- accounting script for MetaCentrum
.SH SYNOPSIS
.B acct-meta
.SH DESCRIPTION
.B acct-meta-json
Script reading binary accounting from STDIN and produce output in JSON format
.SH EXAMPLES 
cat /var/log/account/pacct | ./acct-meta-json
.SH SEE ALSO
.br
.TP
\fBacct-meta\fP(1)
.PD
.SH AUTHOR
Michal Švamberg <svamberg@civ.zcu.cz>
